# Generated by Django 4.1.7 on 2023-05-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='activate',
            field=models.BooleanField(default=True, max_length=6),
        ),
    ]
