# Generated by Django 4.1.9 on 2023-07-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_favjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favjob',
            name='company_icon',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='favjob',
            name='job_company',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='favjob',
            name='job_link',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='favjob',
            name='job_location',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='favjob',
            name='job_title',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='favjob',
            name='listdate',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
